DATA:
  DATASET: tiny-imagenet
  IMG_SIZE: 192
  NUM_WORKERS: 0 # InnoDatahub only
MODEL:
  TYPE: swin_moe
  NAME: swin_moe_tiny_patch4_window6_192_tiny_imnet
  DROP_PATH_RATE: 0.2
  NUM_CLASSES: 200
  SWIN_MOE:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 6
    MLP_FC2_BIAS: False
    INIT_STD: 0.005
    MOE_BLOCKS: [ [ -1 ], [ -1 ], [ 1, 3, 5 ], [ -1 ] ]
    NUM_LOCAL_EXPERTS: 8
    TOP_VALUE: 1
    CAPACITY_FACTOR: 1.25
    IS_GSHARD_LOSS: False
    MOE_DROP: 0.1
    AUX_LOSS_WEIGHT: 0.01
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 10
  WEIGHT_DECAY: 0.1
  BASE_LR: 1.25e-4
  WARMUP_LR: 1.25e-7
  MIN_LR: 1.25e-6
  CLIP_GRAD: 3.0
TEST:
  SHUFFLE: True